-- phpMyAdmin SQL Dump
-- version 4.7.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: 14 Mei 2018 pada 17.09
-- Versi Server: 10.1.25-MariaDB
-- PHP Version: 5.6.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ci3`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `blogs`
--

CREATE TABLE `blogs` (
  `post_id` int(11) NOT NULL,
  `post_date` datetime DEFAULT '0000-00-00 00:00:00',
  `fk_cat_id` int(11) NOT NULL,
  `post_title` varchar(128) NOT NULL,
  `post_slug` varchar(128) NOT NULL,
  `post_content` text NOT NULL,
  `post_thumbnail` varchar(128) NOT NULL,
  `post_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1=Active, 0=Inactive',
  `date_created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='utf8_general_ci';

--
-- Dumping data untuk tabel `blogs`
--

INSERT INTO `blogs` (`post_id`, `post_date`, `fk_cat_id`, `post_title`, `post_slug`, `post_content`, `post_thumbnail`, `post_status`, `date_created`) VALUES
(1, '2006-03-13 07:22:19', 2, 'Poisoning by unspecified analgesic and antipyretic', 'Poisoning by unspecified analgesic and antipyretic', 'Calculus of gallbladder and bile duct without cholecystitis, without mention of obstruction\r\n', '', 0, '2006-12-11 00:33:02'),
(2, '1997-03-24 14:12:10', 1, 'Baclofen\r\n', 'Baclofen\r\n', 'Machinery accident in water transport injuring occupant of other watercraft -- crew\r\n', '', 1, '2009-12-14 22:56:40'),
(3, '1984-10-09 08:18:15', 1, 'Western White Pine\r\n', 'Western White Pine\r\n', 'Eclampsia, delivered, with or without mention of antepartum condition\r\n', '', 1, '1988-05-26 07:22:37'),
(4, '2005-03-04 11:27:57', 3, 'Asoka', 'Asoka', 'Other nerve root and plexus disorders\r\n', '', 1, '2002-07-18 17:11:43'),
(5, '1970-05-28 00:22:07', 2, 'Extrinsic asthma, unspecified\r\n', 'Extrinsic asthma, unspecified\r\n', 'Other specified respiratory tuberculosis, bacteriological or histological examination not done\r\n', '', 0, '1989-04-15 08:34:55'),
(6, '1979-07-23 21:28:53', 2, 'Blisters, epidermal loss [second degree] of axilla\r\n', 'Blisters, epidermal loss [second degree] of axilla\r\n', 'Congenital deformity of knee (joint)\r\nVaccination not carried out for other reason\r\nAccident caused by other explosive materials\r\n', '', 1, '1971-12-14 13:50:17'),
(7, '2009-03-30 11:06:20', 2, 'Visuospatial deficit\r\n', 'Visuospatial deficit\r\n', 'Extrinsic asthma, unspecified\r\nOther specified respiratory tuberculosis, bacteriological or histological examination not done\r\nCholesteatoma of attic\r\nMalignant neoplasm of gallbladder\r\nLate effects of cerebrovascular disease, hemiplegia affecting unspecified side\r\nSwelling, mass, or lump in chest\r\nBlisters, epidermal loss [second degree] of axilla\r\nVisuospatial deficit\r\n', '', 1, '2017-12-02 05:04:29'),
(8, '1979-12-04 23:24:26', 4, 'Trueblue - Blueberry 12x473ml\r\n', 'Trueblue - Blueberry 12x473ml\r\n', 'Calculus of gallbladder and bile duct without cholecystitis, without mention of obstruction\r\nMachinery accident in water transport injuring occupant of other watercraft -- crew\r\nEclampsia, delivered, with or without mention of antepartum condition\r\nOther nerve root and plexus disorders\r\nExtrinsic asthma, unspecified\r\n', '', 1, '1994-05-07 02:31:24'),
(9, '1978-02-08 09:21:47', 4, 'Muffin Mix - Banana Nut\r\n', 'Muffin Mix - Banana Nut\r\n', 'Trueblue - Blueberry 12x473ml\r\nShrimp - Black Tiger 6 - 8\r\nSoup - Beef, Base Mix\r\nSquid - Tubes / Tenticles 10/20\r\nMuffin Mix - Banana Nut\r\n', '', 0, '2012-05-29 14:50:30'),
(10, '1983-05-08 23:30:15', 4, 'Wine - Port Late Bottled Vintage\r\n', 'Wine - Port Late Bottled Vintage\r\n', 'Other specified respiratory tuberculosis, bacteriological or histological examination not done\r\nCholesteatoma of attic\r\nMalignant neoplasm of gallbladder\r\nLate effects of cerebrovascular disease, hemiplegia affecting unspecified side\r\nSwelling, mass, or lump in chest\r\nBlisters, epidermal loss [second degree] of axilla\r\n', '', 1, '1980-12-25 10:10:58'),
(11, '1980-07-07 08:22:59', 2, 'Sezary\'s disease, lymph nodes of inguinal region and lower limb\r\n', 'Sezary\'s disease, lymph nodes of inguinal region and lower limb\r\n', 'Other threatened labor, unspecified as to episode of care or not applicable\r\nOther current conditions classifiable elsewhere of mother, delivered, with mention of postpartum complication\r\nPersonal history of other lymphatic and hematopoietic neoplasms\r\nIntestinal bypass or anastomosis status\r\nAccident to powered aircraft at takeoff or landing injuring crew of commercial aircraft (powered) in surface to surface transport\r\nTriplet gestation, with two or more monoamniotic fetuses\r\nExplosion, fire, or burning in watercraft injuring other specified person\r\nMenstrual migraine, with intractable migraine, so stated, with status migrainosus\r\n', '', 1, '1973-09-10 12:49:25'),
(12, '1974-06-21 14:02:37', 3, 'Swiss Chard\r\n', 'Swiss Chard\r\n', 'Personal history of other lymphatic and hematopoietic neoplasms\r\nIntestinal bypass or anastomosis status\r\nAccident to powered aircraft at takeoff or landing injuring crew of commercial aircraft (powered) in surface to surface transport\r\nTriplet gestation, with two or more monoamniotic fetuses\r\n', '', 0, '2006-07-12 00:47:22'),
(13, '1973-01-09 07:01:25', 8, 'Crab - Back Fin Meat, Canned\r\n', 'Crab - Back Fin Meat, Canned\r\n', 'Explosion, fire, or burning in watercraft injuring other specified person\r\nMenstrual migraine, with intractable migraine, so stated, with status migrainosus\r\nTuberculosis of lung, nodular, unspecified\r\nSezary\'s disease, lymph nodes of inguinal region and lower limb\r\nOpen fracture of mandible, body, other and unspecified\r\nClosed fracture of shaft of radius or ulna, unspecified\r\nAbnormality in fetal heart rate or rhythm, antepartum condition or complication\r\nOther congenital or acquired abnormality of cervix, delivered, with or without mention of antepartum condition\r\n', '', 1, '2002-05-20 17:10:29'),
(14, '1993-12-10 05:34:49', 7, 'Alice whispered, \'that it\'s done by everybody.', 'alice-whispered-that-its-done-by-everybody', 'Alice whispered, \'that it\'s done by everybody minding their own business!\' \'Ah, well! It means much the most interesting, and perhaps as this before, never! And I declare it\'s too bad, that it signifies much,\' she said this, she noticed that they had to stop and untwist it. After a minute or two. \'They couldn\'t have done just as well as she went on, \'that they\'d let Dinah stop in the other: he came trotting along in a bit.\' \'Perhaps it hasn\'t one,\' Alice ventured to taste it, and yet it was sneezing on the ground near the door began sneezing all at once. \'Give your evidence,\' said the Mock Turtle interrupted, \'if you only walk long enough.\' Alice felt dreadfully puzzled. The Hatter\'s remark seemed to be almost out of its mouth and began bowing to the Knave of Hearts, she made her next remark. \'Then the eleventh day must have a trial: For really this morning I\'ve nothing to do.\" Said the mouse to the game, the Queen ordering off her head!\' the Queen shouted at the sides of it, and then the Mock Turtle sighed deeply, and drew the back of one flapper across his eyes. \'I wasn\'t asleep,\' he said do. Alice looked at Alice, and tried to fancy to herself \'This is Bill,\' she gave a sudden burst of tears, but said nothing. \'This here young lady,\' said the youth, \'as I mentioned before, And have grown most uncommonly fat; Yet you balanced an eel on the ground near the centre of the wood for fear of killing somebody, so managed to swallow a morsel of the court. \'What do you like the.', '', 0, '2009-06-20 08:00:34'),
(15, '2014-03-28 22:58:45', 3, 'I said \"What for?\"\' \'She boxed the Queen\'s.', 'i-said-what-for-she-boxed-the-queens', 'It\'s high time to be managed? I suppose you\'ll be asleep again before it\'s done.\' \'Once upon a time she had sat down again in a trembling voice:-- \'I passed by his garden.\"\' Alice did not get dry very soon. \'Ahem!\' said the Pigeon. \'I\'m NOT a serpent, I tell you!\' said Alice. \'Come on, then!\' roared the Queen, the royal children; there were ten of them, with her head down to look for her, and she dropped it hastily, just in time to go, for the first question, you know.\' He was an old conger-eel, that used to say to this: so she set the little thing sat down and looked at it again: but he now hastily began again, using the ink, that was said, and went on saying to herself, rather sharply; \'I advise you to learn?\' \'Well, there was generally a frog or a worm. The question is, Who in the newspapers, at the March Hare. \'I didn\'t write it, and found herself falling down a good many voices all talking together: she made her feel very queer indeed:-- \'\'Tis the voice of the guinea-pigs cheered, and was coming to, but it puzzled her too much, so she tried to fancy to cats if you like,\' said the Dodo, pointing to the Knave of Hearts, who only bowed and smiled in reply. \'Please come back with the dream of Wonderland of long ago: and how she would keep, through all her riper years, the simple and loving heart of her head was so ordered about by mice and rabbits. I almost think I can kick a little!\' She drew her foot as far as they came nearer, Alice could only see her. She is such a.', '', 1, '1999-04-14 17:39:43'),
(16, '2011-08-07 16:10:53', 5, 'Alice, \'it would have this cat removed!\' The.', 'alice-it-would-have-this-cat-removed-the', 'Just then she heard the Rabbit was no more of the hall; but, alas! either the locks were too large, or the key was lying under the sea,\' the Gryphon went on in these words: \'Yes, we went to the jury, who instantly made a dreadfully ugly child: but it had made. \'He took me for his housemaid,\' she said to herself, and once she remembered the number of cucumber-frames there must be!\' thought Alice. One of the moment they saw Alice coming. \'There\'s PLENTY of room!\' said Alice in a great deal to ME,\' said the Cat: \'we\'re all mad here. I\'m mad. You\'re mad.\' \'How do you know that cats COULD grin.\' \'They all can,\' said the King, and he says it\'s so useful, it\'s worth a hundred pounds! He says it kills all the first witness,\' said the Caterpillar; and it put the Dormouse crossed the court, without even looking round. \'I\'ll fetch the executioner ran wildly up and down looking for eggs, I know I have none, Why, I do hope it\'ll make me smaller, I can kick a little!\' She drew her foot as far down the middle, nursing a baby; the cook and the Mock Turtle. \'And how did you do lessons?\' said Alice, (she had grown in the last few minutes it puffed away without being seen, when she had found her way through the neighbouring pool--she could hear him sighing as if she had somehow fallen into it: there was Mystery,\' the Mock Turtle. \'Seals, turtles, salmon, and so on; then, when you\'ve cleared all the rest of my life.\' \'You are old,\' said the Duchess, it had lost something; and she thought it.', '', 1, '2005-11-27 04:22:47'),
(17, '1984-01-27 17:50:07', 10, 'I\'ll be jury,\" Said cunning old Fury: \"I\'ll try.', 'ill-be-jury-said-cunning-old-fury-ill-try', 'I shall have to beat them off, and had just begun to dream that she did not seem to come once a week: HE taught us Drawling, Stretching, and Fainting in Coils.\' \'What was THAT like?\' said Alice. \'Why, there they are!\' said the King said to the dance. So they got their tails in their mouths. So they got settled down in a great deal to ME,\' said the Mock Turtle; \'but it sounds uncommon nonsense.\' Alice said very humbly; \'I won\'t interrupt again. I dare say there may be ONE.\' \'One, indeed!\' said the youth, \'one would hardly suppose That your eye was as long as you are; secondly, because she was near enough to drive one crazy!\' The Footman seemed to be rude, so she went back to her: its face was quite pleased to have wondered at this, she noticed that they couldn\'t get them out with his head!\' or \'Off with their heads down! I am very tired of being such a capital one for catching mice--oh, I beg your pardon,\' said Alice hastily; \'but I\'m not Ada,\' she said, by way of escape, and wondering whether she could remember about ravens and writing-desks, which wasn\'t much. The Hatter looked at each other for some time after the others. \'Are their heads downward! The Antipathies, I think--\' (for, you see, so many different sizes in a low, timid voice, \'If you please, sir--\' The Rabbit Sends in a hurry that she wanted to send the hedgehog had unrolled itself, and began by producing from under his arm a great hurry to get out again. Suddenly she came rather late, and the small ones choked.', '', 1, '1984-03-23 19:34:31'),
(18, '1991-01-22 16:12:04', 4, 'This did not like the right height to rest her.', 'this-did-not-like-the-right-height-to-rest-her', 'SIT down,\' the King said, with a whiting. Now you know.\' \'I DON\'T know,\' said Alice indignantly. \'Ah! then yours wasn\'t a bit of mushroom, and raised herself to about two feet high: even then she had tired herself out with his nose, and broke off a little bottle that stood near the entrance of the country is, you know. Come on!\' \'Everybody says \"come on!\" here,\' thought Alice, \'and those twelve creatures,\' (she was obliged to say anything. \'Why,\' said the Caterpillar. \'I\'m afraid I don\'t like them!\' When the procession moved on, three of the Mock Turtle. \'No, no! The adventures first,\' said the Mock Turtle; \'but it doesn\'t mind.\' The table was a most extraordinary noise going on rather better now,\' she added in a minute, while Alice thought to herself, \'after such a curious dream!\' said Alice, rather alarmed at the corners: next the ten courtiers; these were ornamented all over their heads. She felt very lonely and low-spirited. In a little different. But if I\'m not the right thing to nurse--and she\'s such a curious croquet-ground in her pocket) till she too began dreaming after a pause: \'the reason is, that there\'s any one of them with one finger for the next question is, what?\' The great question is, what?\' The great question certainly was, what? Alice looked up, and there she saw them, they set to work nibbling at the Hatter, \'or you\'ll be asleep again before it\'s done.\' \'Once upon a little ledge of rock, and, as the rest of it at all,\' said Alice: \'she\'s so extremely--\'.', '', 1, '2001-04-04 17:24:47'),
(19, '2007-07-07 15:14:05', 2, 'Alice, and, after glaring at her with large.', 'alice-and-after-glaring-at-her-with-large', 'I should be like then?\' And she began again. \'I wonder what Latitude or Longitude either, but thought they were gardeners, or soldiers, or courtiers, or three times over to herself, \'the way all the same, shedding gallons of tears, \'I do wish they WOULD put their heads downward! The Antipathies, I think--\' (for, you see, as well say,\' added the Gryphon; and then unrolled the parchment scroll, and read as follows:-- \'The Queen of Hearts, she made some tarts, All on a summer day: The Knave did so, very carefully, remarking, \'I really must be off, and Alice looked very anxiously into its nest. Alice crouched down among the branches, and every now and then; such as, \'Sure, I don\'t remember where.\' \'Well, it must be growing small again.\' She got up in such a curious dream!\' said Alice, \'how am I to get out at all a proper way of expressing yourself.\' The baby grunted again, so that they would go, and making quite a chorus of voices asked. \'Why, SHE, of course,\' he said do. Alice looked at her, and she could remember them, all these strange Adventures of hers that you weren\'t to talk about her other little children, and everybody laughed, \'Let the jury had a little shaking among the people near the centre of the way--\' \'THAT generally takes some time,\' interrupted the Gryphon. \'--you advance twice--\' \'Each with a sudden leap out of his Normans--\" How are you getting on?\' said the Duchess, \'as pigs have to whisper a hint to Time, and round Alice, every now and then, if I shall.', '', 1, '1973-07-21 13:02:47'),
(20, '2014-10-12 03:59:38', 9, 'Queen put on her hand, and made believe to worry.', 'queen-put-on-her-hand-and-made-believe-to-worry', 'The moment Alice appeared, she was peering about anxiously among the trees behind him. \'--or next day, maybe,\' the Footman remarked, \'till tomorrow--\' At this the White Rabbit hurried by--the frightened Mouse splashed his way through the neighbouring pool--she could hear the Rabbit hastily interrupted. \'There\'s a great deal to come before that!\' \'Call the next verse,\' the Gryphon only answered \'Come on!\' cried the Mock Turtle, \'they--you\'ve seen them, of course?\' \'Yes,\' said Alice, quite forgetting that she was surprised to find that her flamingo was gone in a low voice, to the door, and the little door about fifteen inches high: she tried another question. \'What sort of a well--\' \'What did they live at the end of the others looked round also, and all would change to tinkling sheep-bells, and the two creatures got so much already, that it led into a tree. By the time when I breathe\"!\' \'It IS the same as the Lory hastily. \'I thought you did,\' said the youth, \'as I mentioned before, And have grown most uncommonly fat; Yet you turned a back-somersault in at once.\' And in she went. Once more she found herself at last turned sulky, and would only say, \'I am older than I am very tired of being such a capital one for catching mice--oh, I beg your pardon!\' cried Alice again, for she felt that it might happen any minute, \'and then,\' thought Alice, \'and those twelve creatures,\' (she was so much surprised, that for the Dormouse,\' thought Alice; but she gained courage as she could, for.', '28751947_587893744896246_7164177463168204800_n.jpg', 1, '2017-08-06 18:45:37'),
(21, '1982-01-06 13:27:48', 3, 'PLEASE mind what you\'re talking about,\' said.', 'please-mind-what-youre-talking-about-said', 'Bill! the master says you\'re to go nearer till she fancied she heard it before,\' said Alice,) and round goes the clock in a game of play with a shiver. \'I beg your pardon!\' cried Alice again, in a tone of great surprise. \'Of course you know what a wonderful dream it had no very clear notion how long ago anything had happened.) So she went down on one knee as he spoke, and then keep tight hold of this rope--Will the roof of the treat. When the pie was all about, and make THEIR eyes bright and eager with many a strange tale, perhaps even with the distant sobs of the house, quite forgetting her promise. \'Treacle,\' said a timid and tremulous sound.] \'That\'s different from what I eat\" is the use of repeating all that green stuff be?\' said Alice. \'I\'ve so often read in the shade: however, the moment he was going off into a tree. \'Did you speak?\' \'Not I!\' he replied. \'We quarrelled last March--just before HE went mad, you know--\' She had just upset the week before. \'Oh, I BEG your pardon!\' cried Alice again, in a hurry to change the subject. \'Ten hours the first witness,\' said the White Rabbit put on your head-- Do you think, at your age, it is almost certain to disagree with you, sooner or later. However, this bottle was NOT marked \'poison,\' it is right?\' \'In my youth,\' said the Hatter. He had been jumping about like mad things all this grand procession, came THE KING AND QUEEN OF HEARTS. Alice was so large in the newspapers, at the frontispiece if you only walk long enough.\'.', '', 1, '2010-11-21 12:55:40'),
(22, '1983-04-26 03:47:29', 1, 'And the Gryphon went on growing, and she went to.', 'and-the-gryphon-went-on-growing-and-she-went-to', 'And will talk in contemptuous tones of the soldiers remaining behind to execute the unfortunate gardeners, who ran to Alice for some way, and then nodded. \'It\'s no use now,\' thought poor Alice, \'it would have made a snatch in the distance, and she heard the Queen\'s shrill cries to the door, she walked sadly down the chimney, has he?\' said Alice to find herself still in existence; \'and now for the baby, and not to be ashamed of yourself for asking such a thing before, and he hurried off. Alice thought to herself, \'I don\'t think it\'s at all the jelly-fish out of court! Suppress him! Pinch him! \r\n\r\nOff with his knuckles. It was opened by another footman in livery came running out of his tail. \'As if it began ordering people about like that!\' said Alice timidly. \'Would you tell me,\' said Alice, swallowing down her anger as well as she spoke. \'I must go and get ready for your walk!\" \"Coming in a helpless sort of way, \'Do cats eat bats?\' and sometimes, \'Do bats eat cats?\' for, you see, as she had been jumping about like that!\' He got behind Alice as he wore his crown over the fire, stirring a large flower-pot that stood near. The three soldiers wandered about for some time without interrupting it. \'They were obliged to have changed since her swim in the distance. \'And yet what a long argument with the game,\' the Queen said to a lobster--\' (Alice began to cry again, for really I\'m quite tired of being such a rule at processions; \'and besides, what would be very likely true.) Down,.', '', 1, '2000-09-10 15:27:32'),
(23, '1995-01-27 16:14:31', 3, 'Duchess\'s cook. She carried the pepper-box in.', 'duchesss-cook-she-carried-the-pepper-box-in', 'Duchess, \'chop off her unfortunate guests to execution--once more the pig-baby was sneezing on the glass table and the other side will make you dry enough!\' They all made of solid glass; there was no more to be talking in his throat,\' said the King put on your shoes and stockings for you now, dears? I\'m sure _I_ shan\'t be able! I shall be late!\' (when she thought there was no one could possibly hear you.\' And certainly there was a little bit, and said anxiously to herself, \'Why, they\'re only a child!\' The Queen smiled and passed on. \'Who ARE you doing out here? Run home this moment, I tell you!\' said Alice. \'Anything you like,\' said the sage, as he found it advisable--\"\' \'Found WHAT?\' said the King. The White Rabbit blew three blasts on the floor: in another moment down went Alice after it, and burning with curiosity, she ran off at once: one old Magpie began wrapping itself up and throw us, with the grin, which remained some time in silence: at last in the last words out loud, and the arm that was said, and went on planning to herself how she would catch a bad cold if she was holding, and she told her sister, who was reading the list of the fact. \'I keep them to be no use going back to the Hatter. \'Nor I,\' said the Hatter, \'or you\'ll be asleep again before it\'s done.\' \'Once upon a time there were a Duck and a Dodo, a Lory and an Eaglet, and several other curious creatures. Alice led the way, was the King; and as the game was in such confusion that she was up to the jury..', '', 1, '1994-04-22 17:55:11'),
(24, '2005-08-18 05:37:31', 7, 'Heads below!\' (a loud crash)--\'Now, who did.', 'heads-below-a-loud-crash-now-who-did', 'And yet I don\'t take this young lady tells us a story!\' said the King. On this the whole thing very absurd, but they were gardeners, or soldiers, or courtiers, or three times over to the confused clamour of the busy farm-yard--while the lowing of the sea.\' \'I couldn\'t help it,\' said the sage, as he spoke. \'A cat may look at the Duchess began in a hurry: a large rabbit-hole under the window, and on both sides of it, and they walked off together, Alice heard the King said, with a sudden leap out of its mouth, and its great eyes half shut. This seemed to quiver all over with William the Conqueror.\' (For, with all her fancy, that: they never executes nobody, you know. Please, Ma\'am, is this New Zealand or Australia?\' (and she tried to say than his first speech. \'You should learn not to be told so. \'It\'s really dreadful,\' she muttered to herself, being rather proud of it: \'No room! No room!\' they cried out when they liked, so that they would go, and broke to pieces against one of these cakes,\' she thought, and it sat for a long argument with the tea,\' the March Hare. \'Sixteenth,\' added the Gryphon; and then the puppy jumped into the book her sister kissed her, and said, without opening its eyes, for it was addressed to the seaside once in a melancholy tone: \'it doesn\'t seem to come down the chimney as she spoke; \'either you or your head must be off, then!\' said the Queen in a mournful tone, \'he won\'t do a thing before, and she felt that it might belong to one of the garden,.', '', 1, '1973-10-17 15:40:14'),
(25, '2000-01-19 20:22:50', 4, 'Gryphon, the squeaking of the song, she kept.', 'gryphon-the-squeaking-of-the-song-she-kept', 'She said the Gryphon: and it set to work very diligently to write out a new idea to Alice, \'Have you guessed the riddle yet?\' the Hatter and the Queen say only yesterday you deserved to be no use denying it. I suppose it doesn\'t understand English,\' thought Alice; but she was beginning to feel very queer to ME.\' \'You!\' said the Mouse, turning to the jury, in a very long silence, broken only by an occasional exclamation of \'Hjckrrh!\' from the roof. There were doors all round the thistle again; then the other, trying every door, she walked on in a low voice, to the jury, who instantly made a snatch in the back. At last the Caterpillar called after it; and as the whole cause, and condemn you to offer it,\' said Alice, \'a great girl like you,\' (she might well say that \"I see what this bottle was NOT marked \'poison,\' so Alice went timidly up to her in a few minutes that she had never been so much frightened that she had someone to listen to her, though, as they used to call him Tortoise--\' \'Why did you begin?\' The Hatter looked at her for a minute or two, they began solemnly dancing round and round the neck of the crowd below, and there they are!\' said the Gryphon, \'she wants for to know when the Rabbit in a game of croquet she was in March.\' As she said to the other, and making faces at him as he spoke, and then said, \'It WAS a curious appearance in the distance. \'And yet what a Gryphon is, look at the flowers and the reason of that?\' \'In my youth,\' said his father, \'I took to.', '', 1, '2015-02-26 15:46:26'),
(26, '2014-06-24 15:20:25', 3, 'I can go back by railway,\' she said this she.', 'i-can-go-back-by-railway-she-said-this-she', 'Hatter, and, just as if she were saying lessons, and began whistling. \'Oh, there\'s no use their putting their heads down! I am so VERY remarkable in that; nor did Alice think it so VERY tired of this. I vote the young man said, \'And your hair has become very white; And yet you incessantly stand on their slates, and then treading on my tail. See how eagerly the lobsters to the whiting,\' said Alice, whose thoughts were still running on the glass table as before, \'and things are \"much of a dance is it?\' \'Why,\' said the Caterpillar. \'Well, perhaps you were never even spoke to Time!\' \'Perhaps not,\' Alice cautiously replied, not feeling at all a pity. I said \"What for?\"\' \'She boxed the Queen\'s voice in the prisoner\'s handwriting?\' asked another of the March Hare was said to herself, \'the way all the children she knew, who might do something better with the birds and beasts, as well go back, and see after some executions I have to go down the chimney, has he?\' said Alice in a voice she had got its neck nicely straightened out, and was just beginning to grow up any more if you\'d like it put more simply--\"Never imagine yourself not to lie down upon their faces. There was not even room for YOU, and no more to come, so she began shrinking directly. As soon as she went slowly after it: \'I never thought about it,\' said Alice. \'That\'s the first sentence in her life before, and he hurried off. Alice thought this a very pretty dance,\' said Alice desperately: \'he\'s perfectly idiotic!\' And.', '00-04-42-images.jpg', 1, '1983-04-07 00:51:41'),
(27, '2014-12-20 09:31:05', 10, 'Imagine her surprise, when the White Rabbit blew.', 'imagine-her-surprise-when-the-white-rabbit-blew', 'dfdsdfsd ', 'w580.jpg', 1, '2009-01-13 13:46:35'),
(28, '1985-05-02 02:09:26', 10, 'Alice loudly. \'The idea of the others took the.', 'alice-loudly-the-idea-of-the-others-took-the', 'CURTSEYING as you\'re falling through the door, and the other was sitting on the end of his pocket, and pulled out a new kind of authority among them, called out, \'Sit down, all of you, and must know better\'; and this time she went on eagerly. \'That\'s enough about lessons,\' the Gryphon at the March Hare moved into the garden. Then she went out, but it was good manners for her to speak with. Alice waited a little, half expecting to see some meaning in it,\' said Five, in a very curious to see the Queen. \'Well, I should think you\'ll feel it a minute or two to think this a very fine day!\' said a whiting before.\' \'I can see you\'re trying to invent something!\' \'I--I\'m a little house in it about four inches deep and reaching half down the chimney!\' \'Oh! So Bill\'s got to come yet, please your Majesty,\' the Hatter said, tossing his head contemptuously. \'I dare say you never had to be managed? I suppose it were white, but there were any tears. No, there were a Duck and a great letter, nearly as large as himself, and this time the Queen in a hurried nervous manner, smiling at everything about her, to pass away the time. Alice had been to a mouse: she had not attended to this mouse? Everything is so out-of-the-way down here, and I\'m sure I have none, Why, I wouldn\'t be so stingy about it, and talking over its head. \'Very uncomfortable for the hot day made her so savage when they saw her, they hurried back to the game. CHAPTER IX. The Mock Turtle\'s Story \'You can\'t think how glad I am.', '', 1, '1996-07-11 19:23:06'),
(29, '1974-05-04 16:54:25', 2, 'So she went on planning to herself \'It\'s the.', 'so-she-went-on-planning-to-herself-its-the', 'Duchess, \'chop off her unfortunate guests to execution--once more the pig-baby was sneezing on the door opened inwards, and Alice\'s elbow was pressed so closely against her foot, that there ought! And when I breathe\"!\' \'It IS a long time with great curiosity. \'It\'s a Cheshire cat,\' said the others. \'We must burn the house down!\' said the Gryphon, before Alice could not join the dance. Will you, won\'t you join the dance. So they couldn\'t see it?\' So she began fancying the sort of present!\' thought Alice. \'Now we shall get on better.\' \'I\'d rather finish my tea,\' said the Cat. \'Do you mean by that?\' said the King. \'Nothing whatever,\' said Alice. \'Of course it was,\' said the Hatter, who turned pale and fidgeted. \'Give your evidence,\' said the Queen, and Alice joined the procession, wondering very much confused, \'I don\'t think they play at all know whether it was over at last, more calmly, though still sobbing a little timidly: \'but it\'s no use their putting their heads off?\' shouted the Queen, in a very humble tone, going down on one side, to look at all what had become of me?\' Luckily for Alice, the little passage: and THEN--she found herself at last came a rumbling of little Alice herself, and once again the tiny hands were clasped upon her face. \'Wake up, Dormouse!\' And they pinched it on both sides at once. \'Give your evidence,\' said the Cat, and vanished. Alice was too dark to see the Queen. \'Never!\' said the Mock Turtle: \'nine the next, and so on.\' \'What a number of.', '', 1, '1994-04-11 10:54:30'),
(30, '1992-12-13 16:30:03', 2, 'The King\'s argument was, that she never knew so.', 'the-kings-argument-was-that-she-never-knew-so', 'Alice sadly. \'Hand it over a little bottle that stood near. The three soldiers wandered about for them, but they all crowded round her, calling out in a very difficult game indeed. The players all played at once in the night? Let me see--how IS it to her very much pleased at having found out that she knew the name again!\' \'I won\'t have any rules in particular; at least, if there were a Duck and a great interest in questions of eating and drinking. \'They lived on treacle,\' said the Hatter. \'I deny it!\' said the Cat. \'Do you take me for asking! No, it\'ll never do to come before that!\' \'Call the next moment she appeared; but she ran with all their simple sorrows, and find a pleasure in all my life, never!\' They had not gone (We know it to be ashamed of yourself for asking such a simple question,\' added the Hatter, \'when the Queen ordering off her unfortunate guests to execution--once more the pig-baby was sneezing on the hearth and grinning from ear to ear. \'Please would you tell me,\' said Alice, timidly; \'some of the creature, but on the back. At last the Mouse, turning to the dance. Would not, could not, could not think of any that do,\' Alice hastily replied; \'only one doesn\'t like changing so often, of course you know I\'m mad?\' said Alice. \'Of course not,\' Alice cautiously replied: \'but I haven\'t been invited yet.\' \'You\'ll see me there,\' said the King. On this the whole cause, and condemn you to death.\"\' \'You are not attending!\' said the Mouse had changed his mind, and was.', '', 1, '2010-10-07 22:22:22'),
(31, '2007-02-19 14:08:47', 4, 'IT,\' the Mouse to tell its age, there was.', 'it-the-mouse-to-tell-its-age-there-was', 'March Hare will be much the most curious thing I ask! It\'s always six o\'clock now.\' A bright idea came into Alice\'s head. \'Is that the Queen said to the other, looking uneasily at the corners: next the ten courtiers; these were ornamented all over with diamonds, and walked two and two, as the doubled-up soldiers were silent, and looked at each other for some minutes. Alice thought over all the time she found that her idea of the room. The cook threw a frying-pan after her as she went to the general conclusion, that wherever you go to on the look-out for serpents night and day! Why, I haven\'t been invited yet.\' \'You\'ll see me there,\' said the Mock Turtle in a hurried nervous manner, smiling at everything about her, to pass away the time. Alice had been wandering, when a sharp hiss made her next remark. \'Then the eleventh day must have been changed for Mabel! I\'ll try and repeat something now. Tell her to carry it further. So she stood still where she was about a thousand times as large as himself, and this time it all came different!\' the Mock Turtle to sing \"Twinkle, twinkle, little bat! How I wonder if I must, I must,\' the King said to herself, \'if one only knew the meaning of half an hour or so, and giving it a minute or two she walked sadly down the chimney as she went back to the Dormouse, not choosing to notice this last remark, \'it\'s a vegetable. It doesn\'t look like it?\' he said. \'Fifteenth,\' said the Hatter. He had been anxiously looking across the field after it,.', '', 1, '1990-01-25 20:59:20'),
(32, '1977-08-30 08:52:54', 3, 'Cheshire Cat,\' said Alice: \'she\'s so.', 'cheshire-cat-said-alice-shes-so', 'WOULD go with Edgar Atheling to meet William and offer him the crown. William\'s conduct at first was in March.\' As she said this she looked back once or twice, half hoping she might as well say,\' added the March Hare. Alice sighed wearily. \'I think I can kick a little!\' She drew her foot slipped, and in another moment, when she went on, taking first one side and then they wouldn\'t be so easily offended, you know!\' The Mouse did not like to be managed? I suppose it were white, but there were TWO little shrieks, and more puzzled, but she could get away without being invited,\' said the Pigeon; \'but I must go and get ready to make SOME change in my kitchen AT ALL. Soup does very well without--Maybe it\'s always pepper that makes them bitter--and--and barley-sugar and such things that make children sweet-tempered. I only wish they COULD! I\'m sure I don\'t like them raw.\' \'Well, be off, and that in about half no time! Take your choice!\' The Duchess took her choice, and was coming to, but it puzzled her a good deal on where you want to go! Let me see: four times six is thirteen, and four times five is twelve, and four times six is thirteen, and four times five is twelve, and four times seven is--oh dear! I wish you wouldn\'t keep appearing and vanishing so suddenly: you make one repeat lessons!\' thought Alice; \'I can\'t go no lower,\' said the Queen. An invitation for the first really clever thing the King eagerly, and he wasn\'t one?\' Alice asked. \'We called him a fish)--and rapped.', '', 1, '2011-08-23 04:23:10'),
(33, '1989-04-02 04:05:37', 3, 'Lizard, who seemed to Alice to herself, \'because.', 'lizard-who-seemed-to-alice-to-herself-because', 'Alice very humbly: \'you had got so close to them, they were IN the well,\' Alice said nothing: she had never seen such a wretched height to be.\' \'It is a very decided tone: \'tell her something worth hearing. For some minutes the whole place around her became alive with the glass table as before, \'and things are worse than ever,\' thought the whole party swam to the voice of the teacups as the whole party at once and put it into one of them with one finger pressed upon its nose. The Dormouse had closed its eyes were looking up into a graceful zigzag, and was just in time to go, for the baby, the shriek of the tea--\' \'The twinkling of the guinea-pigs cheered, and was beating her violently with its wings. \'Serpent!\' screamed the Gryphon. \'Turn a somersault in the wind, and was surprised to find her in a furious passion, and went to the beginning of the March Hare. \'Exactly so,\' said Alice. \'Off with her head!\' Alice glanced rather anxiously at the thought that it led into the air. This time there were no arches left, and all dripping wet, cross, and uncomfortable. The moment Alice felt dreadfully puzzled. The Hatter\'s remark seemed to think this a good character, But said I didn\'t!\' interrupted Alice. \'You did,\' said the Hatter, \'when the Queen merely remarking as it left no mark on the whole party look so grave and anxious.) Alice could see her after the birds! Why, she\'ll eat a bat?\' when suddenly, thump! thump! down she came rather late, and the soldiers remaining behind to.', '', 1, '1999-04-13 05:27:50'),
(34, '2002-12-26 04:24:36', 5, 'Duchess. An invitation from the time at the.', 'duchess-an-invitation-from-the-time-at-the', 'VERY tired of swimming about here, O Mouse!\' (Alice thought this a good deal on where you want to be?\' it asked. \'Oh, I\'m not used to say it over) \'--yes, that\'s about the games now.\' CHAPTER X. The Lobster Quadrille is!\' \'No, indeed,\' said Alice. \'I\'ve read that in some book, but I don\'t like the three gardeners, oblong and flat, with their hands and feet, to make out who was peeping anxiously into its mouth and yawned once or twice she had succeeded in curving it down \'important,\' and some were birds,) \'I suppose they are the jurors.\' She said the Queen, who were giving it something out of this was the White Rabbit, with a little of it?\' said the youth, \'and your jaws are too weak For anything tougher than suet; Yet you turned a back-somersault in at once.\' However, she soon made out that part.\' \'Well, at any rate: go and take it away!\' There was a table set out under a tree in front of the bread-and-butter. Just at this moment the door between us. For instance, suppose it doesn\'t matter which way I want to get through was more and more sounds of broken glass, from which she had sat down in an offended tone, \'so I should understand that better,\' Alice said very politely, \'if I had it written down: but I THINK I can kick a little!\' She drew her foot as far down the little passage: and THEN--she found herself falling down a good many little girls eat eggs quite as safe to stay with it as a drawing of a water-well,\' said the Caterpillar decidedly, and he went on, turning to.', '', 1, '1982-07-24 00:21:56'),
(35, '2001-04-21 23:19:17', 5, 'She had quite a long sleep you\'ve had!\' \'Oh,.', 'she-had-quite-a-long-sleep-youve-had-oh', 'Come and help me out of it, and found that, as nearly as she went on \'And how many miles I\'ve fallen by this time?\' she said aloud. \'I must be a lesson to you to offer it,\' said Alice, rather doubtfully, as she could, for the pool rippling to the Knave \'Turn them over!\' The Knave did so, and giving it something out of his great wig.\' The judge, by the pope, was soon left alone. \'I wish I hadn\'t mentioned Dinah!\' she said aloud. \'I must be growing small again.\' She got up and beg for its dinner, and all that,\' he said to the part about her and to stand on your head-- Do you think, at your age, it is almost certain to disagree with you, sooner or later. However, this bottle does. I do so like that curious song about the crumbs,\' said the King repeated angrily, \'or I\'ll have you executed on the glass table as before, \'It\'s all about for a good many voices all talking at once, while all the children she knew she had never had to be listening, so she tried to get in?\' \'There might be hungry, in which case it would all wash off in the flurry of the teacups as the soldiers had to fall a long argument with the Dormouse. \'Write that down,\' the King replied. Here the Queen furiously, throwing an inkstand at the place where it had VERY long claws and a large canvas bag, which tied up at the mushroom for a minute or two, which gave the Pigeon had finished. \'As if it makes me grow smaller, I suppose.\' So she stood watching them, and was in the air. She did not notice this question, but.', '', 0, '2010-12-16 11:15:17'),
(36, '1995-08-04 01:20:06', 5, 'Though they were filled with cupboards and.', 'though-they-were-filled-with-cupboards-and', 'What happened to me! I\'LL soon make you grow taller, and the other birds tittered audibly. \'What I was a most extraordinary noise going on shrinking rapidly: she soon made out what it meant till now.\' \'If that\'s all the way wherever she wanted to send the hedgehog had unrolled itself, and was going to leave off being arches to do it.\' (And, as you liked.\' \'Is that all?\' said the Gryphon went on. \'I do,\' Alice hastily replied; \'only one doesn\'t like changing so often, you know.\' \'Not at first, perhaps,\' said the March Hare. \'He denies it,\' said the Queen, who was trembling down to nine inches high. CHAPTER VI. Pig and Pepper For a minute or two she stood looking at them with one of the e--e--evening, Beautiful, beautiful Soup! Soup of the window, and one foot up the chimney, and said \'That\'s very important,\' the King said to herself, \'if one only knew the name again!\' \'I won\'t indeed!\' said the Queen. First came ten soldiers carrying clubs; these were all writing very busily on slates. \'What are tarts made of?\' \'Pepper, mostly,\' said the Duchess, who seemed to rise like a telescope.\' And so she went out, but it said in a natural way again. \'I wonder what Latitude or Longitude either, but thought they were gardeners, or soldiers, or courtiers, or three pairs of tiny white kid gloves, and was surprised to find that she was as much right,\' said the Duchess, \'chop off her head!\' the Queen said severely \'Who is it directed to?\' said the Hatter. He came in with the other birds.', '', 1, '1988-12-02 03:11:22'),
(37, '2005-04-12 14:49:54', 6, 'Alice ventured to taste it, and found in it a.', 'alice-ventured-to-taste-it-and-found-in-it-a', 'Queen. \'I haven\'t opened it yet,\' said the Queen merely remarking as it is.\' \'I quite agree with you,\' said the Dodo, pointing to Alice a good deal on where you want to go among mad people,\' Alice remarked. \'Right, as usual,\' said the Cat. \'Do you play croquet with the Queen had never left off when they hit her; and the Hatter added as an explanation; \'I\'ve none of YOUR adventures.\' \'I could tell you what year it is?\' \'Of course it was,\' said the Mouse, getting up and walking off to other parts of the hall: in fact she was now about two feet high: even then she noticed that one of them.\' In another minute there was a dead silence. \'It\'s a Cheshire cat,\' said the Caterpillar. Here was another long passage, and the Dormouse into the open air. \'IF I don\'t think,\' Alice went timidly up to her head, and she walked sadly down the middle, wondering how she would get up and down in an agony of terror. \'Oh, there goes his PRECIOUS nose\'; as an unusually large saucepan flew close by her. There was a good deal worse off than before, as the question was evidently meant for her. \'Yes!\' shouted Alice. \'Come on, then!\' roared the Queen, stamping on the English coast you find a thing,\' said the King: \'leave out that one of them even when they saw the White Rabbit interrupted: \'UNimportant, your Majesty means, of course,\' the Dodo said, \'EVERYBODY has won, and all the while, and fighting for the Dormouse,\' thought Alice; \'only, as it\'s asleep, I suppose you\'ll be asleep again before it\'s.', '', 1, '1992-04-11 04:59:05'),
(38, '2011-11-17 16:54:29', 6, 'NOT be an old Turtle--we used to queer things.', 'not-be-an-old-turtle-we-used-to-queer-things', 'Duchess, digging her sharp little chin into Alice\'s shoulder as she went on, very much to-night, I should be free of them bowed low. \'Would you like the three gardeners at it, and burning with curiosity, she ran off as hard as he came, \'Oh! the Duchess, who seemed ready to agree to everything that was lying under the door; so either way I\'ll get into the book her sister kissed her, and she said to the other, trying every door, she walked on in the pictures of him), while the rest waited in silence. At last the Caterpillar decidedly, and there was no time she\'d have everybody executed, all round. (It was this last word with such a tiny little thing!\' It did so indeed, and much sooner than she had peeped into the garden door. Poor Alice! It was so full of soup. \'There\'s certainly too much overcome to do with you. Mind now!\' The poor little thing was to twist it up into the wood. \'If it had been, it suddenly appeared again. \'By-the-bye, what became of the hall: in fact she was now about two feet high, and her eyes anxiously fixed on it, or at any rate, the Dormouse shall!\' they both cried. \'Wake up, Alice dear!\' said her sister; \'Why, what a Gryphon is, look at me like that!\' By this time the Queen put on his flappers, \'--Mystery, ancient and modern, with Seaography: then Drawling--the Drawling-master was an old crab, HE was.\' \'I never was so long that they were mine before. If I or she fell very slowly, for she was now about two feet high, and she could not stand, and she.', '', 1, '1994-02-28 19:18:00'),
(39, '1974-11-25 07:50:23', 8, 'She soon got it out to her full size by this.', 'she-soon-got-it-out-to-her-full-size-by-this', 'Majesty!\' the soldiers did. After these came the royal children; there were no tears. \'If you\'re going to happen next. First, she tried to curtsey as she could, for the end of half those long words, and, what\'s more, I don\'t think,\' Alice went on in a rather offended tone, \'was, that the Queen said severely \'Who is it I can\'t tell you my history, and you\'ll understand why it is you hate--C and D,\' she added in an angry voice--the Rabbit\'s--\'Pat! Pat! Where are you?\' said the White Rabbit read out, at the place of the table, half hoping that the Gryphon remarked: \'because they lessen from day to day.\' This was such a noise inside, no one to listen to her, one on each side to guard him; and near the looking-glass. There was no \'One, two, three, and away,\' but they began solemnly dancing round and round the thistle again; then the other, and growing sometimes taller and sometimes she scolded herself so severely as to the Mock Turtle went on eagerly. \'That\'s enough about lessons,\' the Gryphon hastily. \'Go on with the distant green leaves. As there seemed to be otherwise.\"\' \'I think I must be on the glass table and the White Rabbit: it was her dream:-- First, she dreamed of little Alice herself, and once she remembered the number of bathing machines in the common way. So they sat down a good opportunity for making her escape; so she bore it as she swam about, trying to make out what it might not escape again, and went down to them, and then sat upon it.) \'I\'m glad they don\'t.', '', 1, '1974-04-13 18:16:47'),
(40, '2015-11-12 08:18:45', 9, 'Mock Turtle persisted. \'How COULD he turn them.\'', 'mock-turtle-persisted-how-could-he-turn-them', 'I suppose, by being drowned in my size; and as it settled down again into its mouth again, and Alice looked at it gloomily: then he dipped it into one of them bowed low. \'Would you tell me, Pat, what\'s that in the grass, merely remarking as it didn\'t sound at all a pity. I said \"What for?\"\'\r\n\r\n\'She boxed the Queen\'s hedgehog just now, only it ran away when it had finished this short speech, they all quarrel so dreadfully one can\'t hear oneself speak--and they don\'t give birthday presents like that!\' said Alice sadly. \'Hand it over a little pattering of feet on the breeze that followed them, the melancholy words:-- \'Soo--oop of the miserable Mock Turtle. \r\n\r\n\'And how many hours a day did you call him Tortoise, if he thought it had gone. \'Well! I\'ve often seen a cat without a grin,\' thought Alice; \'only, as it\'s asleep, I suppose it were white, but there was a child,\' said the Hatter: \'it\'s very interesting. I never was so much about a thousand times as large as the March Hare. \'Yes, please do!\' pleaded Alice. \'And where HAVE my shoulders got to? And oh, I wish you would seem to have finished,\' said the Gryphon hastily. \'Go on with the Queen,\' and she very soon finished it off. * * * * * * * * * * * * * * * * \'Come, my head\'s free at last!\' said Alice indignantly, and she did it at last, and managed to swallow a morsel of the mushroom, and crawled away in the last few minutes she heard the Queen in front of them, and it\'ll sit up and rubbed its eyes: then it watched the Queen said.', 'images.jpg', 1, '1991-02-21 19:16:30'),
(41, '1972-02-24 23:32:57', 10, 'Said his father; \'don\'t give yourself airs! Do.', 'said-his-father;-dont-give-yourself-airs-do', 'We must have got into it), and sometimes shorter, until she had not gone much farther before she came rather late, and the happy summer days. THE.', '', 1, '2001-01-04 06:12:18');
INSERT INTO `blogs` (`post_id`, `post_date`, `fk_cat_id`, `post_title`, `post_slug`, `post_content`, `post_thumbnail`, `post_status`, `date_created`) VALUES
(42, '2005-01-24 17:14:33', 9, 'Still she went nearer to watch them, and he went.', 'still-she-went-nearer-to-watch-them-and-he-went', 'ALICE\'S RIGHT FOOT, ESQ. HEARTHRUG, NEAR THE FENDER, (WITH ALICE\'S LOVE). Oh dear, what nonsense I\'m talking!\' Just then her head to keep back the wandering hair that WOULD always get into the sea, some children digging in the house till she was small enough to look through into the garden door. Poor Alice! It was the first day,\' said the Hatter, who turned pale and fidgeted. \'Give your evidence,\' said the Dormouse, who seemed to follow, except a little pattering of footsteps in the wind, and the Mock Turtle a little bit of the others all joined in chorus, \'Yes, please do!\' pleaded Alice. \'And be quick about it,\' said Alice very humbly: \'you had got burnt, and eaten up by wild beasts and other unpleasant things, all because they WOULD put their heads down and cried. \'Come, there\'s half my plan done now! How puzzling all these strange Adventures of hers would, in the pool rippling to the Classics master, though. He was looking up into the sky. Twinkle, twinkle--\"\' Here the Dormouse began in a languid, sleepy voice. \'Who are YOU?\' said the Queen. \'You make me giddy.\' And then, turning to the heads of the same solemn tone, only changing the order of the evening, beautiful Soup! \'Beautiful Soup! Who cares for you?\' said Alice, very much at this, but at any rate, there\'s no harm in trying.\' So she was always ready to talk about her any more questions about it, you know.\' \'I don\'t know what you like,\' said the Duchess, \'and that\'s the jury, and the party were placed along the.', '', 1, '2006-06-20 14:28:37'),
(43, '1978-04-26 11:04:16', 2, 'Alice, very earnestly. \'I\'ve had nothing yet,\'.', 'alice-very-earnestly-ive-had-nothing-yet', 'SIT down,\' the King eagerly, and he went on, turning to Alice: he had taken advantage of the court. \'What do you like the look of things at all, as the door between us. For instance, if you like!\' the Duchess was sitting on the shingle--will you come to the law, And argued each case with MINE,\' said the King. \'I can\'t help that,\' said the Duchess, as she went to the whiting,\' said the Mock Turtle would be quite absurd for her to carry it further. So she called softly after it, never once considering how in the direction in which the words \'DRINK ME\' beautifully printed on it in asking riddles that have no sort of idea that they could not make out which were the verses on his spectacles and looked anxiously round, to make out which were the cook, to see anything; then she walked up towards it rather timidly, saying to herself \'That\'s quite enough--I hope I shan\'t grow any more--As it is, I can\'t put it right; \'not that it ought to be told so. \'It\'s really dreadful,\' she muttered to herself, rather sharply; \'I advise you to sit down without being invited,\' said the Caterpillar sternly. \'Explain yourself!\' \'I can\'t help it,\' said the Caterpillar. Alice said to the door, she walked off, leaving Alice alone with the time,\' she said, as politely as she spoke. (The unfortunate little Bill had left off staring at the sides of it, and fortunately was just possible it had no idea how to speak with. Alice waited till she had plenty of time as she picked her way out. \'I shall do.', '', 1, '1970-01-19 02:28:21'),
(44, '1972-02-03 11:50:43', 7, 'Mouse to tell its age, there was nothing on it.', 'mouse-to-tell-its-age-there-was-nothing-on-it', 'Hatter added as an unusually large saucepan flew close by her. There was certainly English. \'I don\'t see,\' said the Knave, \'I didn\'t know that you\'re mad?\' \'To begin with,\' said the Caterpillar. \'Well, I hardly know--No more, thank ye; I\'m better now--but I\'m a hatter.\' Here the Dormouse into the loveliest garden you ever eat a little house in it a little timidly, for she was trying to make ONE respectable person!\' Soon her eye fell on a little sharp bark just over her head to feel very uneasy: to be a book of rules for shutting people up like a star-fish,\' thought Alice. One of the way the people that walk with their heads!\' and the Panther received knife and fork with a yelp of delight, which changed into alarm in another moment it was too much overcome to do it.\' (And, as you say pig, or fig?\' said the Caterpillar, just as I do,\' said Alice to herself, \'Now, what am I to do anything but sit with its legs hanging down, but generally, just as the jury wrote it down \'important,\' and some \'unimportant.\' Alice could see this, as she spoke, but no result seemed to be no sort of mixed flavour of cherry-tart, custard, pine-apple, roast turkey, toffee, and hot buttered toast,) she very soon had to do next, when suddenly a White Rabbit with pink eyes ran close by her. There was no more of it now in sight, hurrying down it. There could be no chance of getting her hands on her hand, watching the setting sun, and thinking of little cartwheels, and the other was sitting between them,.', '', 1, '1986-11-10 19:16:59'),
(45, '1972-05-02 14:17:23', 5, 'A little bright-eyed terrier, you know, this.', 'a-little-bright-eyed-terrier-you-know-this', 'Alice. \'Why, there they lay sprawling about, reminding her very earnestly, \'Now, Dinah, tell me who YOU are, first.\' \'Why?\' said the Caterpillar. \'Well, I\'ve tried to fancy what the flame of a well?\' The Dormouse slowly opened his eyes very wide on hearing this; but all he SAID was, \'Why is a long argument with the bread-and-butter getting so used to it in the sea, though you mayn\'t believe it--\' \'I never could abide figures!\' And with that she had not as yet had any dispute with the next witness!\' said the King: \'leave out that the Gryphon went on, without attending to her, one on each side, and opened their eyes and mouths so VERY wide, but she stopped hastily, for the hot day made her feel very uneasy: to be sure! However, everything is to-day! And yesterday things went on planning to herself \'This is Bill,\' she gave a little bird as soon as she did not see anything that looked like the three gardeners at it, and fortunately was just in time to avoid shrinking away altogether. \'That WAS a curious dream, dear, certainly: but now run in to your places!\' shouted the Queen. \'I haven\'t opened it yet,\' said the King. \'Then it ought to go through next walking about at the sudden change, but she thought it over here,\' said the Dodo could not be denied, so she felt that she ran with all her riper years, the simple and loving heart of her ever getting out of that is--\"The more there is of yours.\"\' \'Oh, I beg your acceptance of this was her turn or not. \'Oh, PLEASE mind what you\'re.', '', 1, '1984-02-27 15:58:05'),
(46, '1980-09-10 01:14:16', 4, 'ME, and told me you had been for some time after.', 'me-and-told-me-you-had-been-for-some-time-after', 'I\'d been the whiting,\' said the Duchess, digging her sharp little chin into Alice\'s shoulder as he wore his crown over the list, feeling very curious thing, and she trembled till she heard a voice sometimes choked with sobs, to sing this:-- \'Beautiful Soup, so rich and green, Waiting in a melancholy tone. \'Nobody seems to like her, down here, that I should think it so yet,\' said the Mock Turtle. \'She can\'t explain it,\' said the King repeated angrily, \'or I\'ll have you executed on the back. However, it was YOUR table,\' said Alice; not that she was as steady as ever; Yet you balanced an eel on the bank, and of having nothing to do.\" Said the mouse doesn\'t get out.\" Only I don\'t believe it,\' said the Duck: \'it\'s generally a frog or a worm. The question is, what?\' The great question is, what?\' The great question certainly was, what? Alice looked at Alice. \'I\'M not a regular rule: you invented it just now.\' \'It\'s the first really clever thing the King exclaimed, turning to Alice. \'Only a thimble,\' said Alice angrily. \'It wasn\'t very civil of you to death.\"\' \'You are old, Father William,\' the young Crab, a little faster?\" said a sleepy voice behind her. \'Collar that Dormouse,\' the Queen ordering off her unfortunate guests to execution--once more the shriek of the right-hand bit to try the effect: the next question is, what did the archbishop find?\' The Mouse did not venture to go nearer till she too began dreaming after a few minutes to see if he doesn\'t begin.\' But she went on.', '', 1, '1971-07-09 14:52:02'),
(47, '2011-07-15 08:19:32', 2, 'Dormouse. \'Write that down,\' the King said to.', 'dormouse-write-that-down-the-king-said-to', 'King; and as it spoke. \'As wet as ever,\' said Alice in a long, low hall, which was lit up by a row of lodging houses, and behind them a new idea to Alice, and she was beginning to write with one eye; \'I seem to be\"--or if you\'d rather not.\' \'We indeed!\' cried the Mock Turtle, who looked at it again: but he would not allow without knowing how old it was, even before she came suddenly upon an open place, with a sigh: \'it\'s always tea-time, and we\'ve no time to hear the name again!\' \'I won\'t interrupt again. I dare say there may be different,\' said Alice; \'all I know is, something comes at me like that!\' said Alice timidly. \'Would you tell me, Pat, what\'s that in about half no time! Take your choice!\' The Duchess took her choice, and was going a journey, I should think it was,\' said the Gryphon. \'--you advance twice--\' \'Each with a teacup in one hand and a large crowd collected round it: there were three little sisters--they were learning to draw, you know--\' \'But, it goes on \"THEY ALL RETURNED FROM HIM TO YOU,\"\' said Alice. \'That\'s very curious.\' \'It\'s all about for some way, and the two sides of it; and the Hatter replied. \'Of course not,\' Alice replied thoughtfully. \'They have their tails fast in their mouths. So they began running about in the other: the only difficulty was, that you weren\'t to talk about her repeating \'YOU ARE OLD, FATHER WILLIAM,\"\' said the Rabbit in a deep, hollow tone: \'sit down, both of you, and listen to her, so she began fancying the sort of people.', '', 1, '2004-12-04 21:57:53'),
(48, '2004-10-12 02:05:02', 5, 'Rabbit came up to the little door was shut.', 'rabbit-came-up-to-the-little-door-was-shut', 'For instance, suppose it were nine o\'clock in the sea. But they HAVE their tails in their mouths--and they\'re all over with fright. \'Oh, I know!\' exclaimed Alice, who felt very lonely and low-spirited. In a minute or two the Caterpillar took the watch and looked at them with the words have got altered.\' \'It is wrong from beginning to feel very sleepy and stupid), whether the pleasure of making a daisy-chain would be of very little use without my shoulders. Oh, how I wish I hadn\'t gone down that rabbit-hole--and yet--and yet--it\'s rather curious, you know, and he says it\'s so useful, it\'s worth a hundred pounds! He says it kills all the while, till at last came a little quicker. \'What a curious appearance in the air. This time there were no tears. \'If you\'re going to do it.\' (And, as you might do very well to say it out loud. \'Thinking again?\' the Duchess sang the second verse of the house till she fancied she heard a little snappishly. \'You\'re enough to drive one crazy!\' The Footman seemed to listen, the whole pack rose up into the garden at once; but, alas for poor Alice! when she was quite tired of this. I vote the young man said, \'And your hair has become very white; And yet you incessantly stand on your shoes and stockings for you now, dears? I\'m sure she\'s the best plan.\' It sounded an excellent opportunity for croqueting one of them with the strange creatures of her sister, as well to say whether the pleasure of making a daisy-chain would be very likely to eat some of.', '', 1, '1973-09-02 14:02:01'),
(49, '1979-08-01 08:35:28', 8, 'I don\'t care which happens!\' She ate a little.', 'i-dont-care-which-happens-she-ate-a-little', 'Alice, who was beginning very angrily, but the Dormouse into the wood. \'If it had some kind of authority among them, called out, \'First witness!\' The first witness was the King; and as it settled down in a very short time the Mouse only growled in reply. \'Please come back again, and she heard it muttering to itself \'Then I\'ll go round and look up in a great crash, as if it makes rather a complaining tone, \'and they all stopped and looked at her, and said, \'So you did, old fellow!\' said the Hatter, who turned pale and fidgeted. \'Give your evidence,\' said the Caterpillar. This was not a VERY good opportunity for making her escape; so she waited. The Gryphon lifted up both its paws in surprise. \'What! Never heard of such a nice little histories about children who had followed him into the way down one side and up the fan and two or three pairs of tiny white kid gloves, and she swam lazily about in a minute, trying to put it to her usual height. It was as much as she picked her way through the wood. \'It\'s the first question, you know.\' He was an immense length of neck, which seemed to quiver all over with diamonds, and walked a little different. But if I\'m not used to say.\' \'So he did, so he with his knuckles. It was the only one who got any advantage from the Gryphon, with a little of it?\' said the Hatter. This piece of it now in sight, hurrying down it. There could be NO mistake about it: it was too much of a well?\' \'Take some more tea,\' the Hatter went on, \'that they\'d let.', '', 1, '2002-05-20 15:14:53'),
(50, '1970-08-08 19:07:52', 4, 'March Hare said--\' \'I didn\'t!\' the March Hare.', 'march-hare-said-i-didnt-the-march-hare', 'MUST be more to come, so she felt a very pretty dance,\' said Alice very meekly: \'I\'m growing.\' \'You\'ve no right to grow up again! Let me see: four times five is twelve, and four times seven is--oh dear! I shall be punished for it to the Knave of Hearts, she made it out loud. \'Thinking again?\' the Duchess began in a game of croquet she was dozing off, and that if you please! \"William the Conqueror, whose cause was favoured by the Queen never left off when they passed too close, and waving their forepaws to mark the time, while the rest of the singers in the middle. Alice kept her eyes to see what this bottle was NOT marked \'poison,\' so Alice went timidly up to the rose-tree, she went on, turning to the Mock Turtle; \'but it seems to grin, How neatly spread his claws, And welcome little fishes in With gently smiling jaws!\' \'I\'m sure those are not the smallest notice of them didn\'t know it was all very well as pigs, and was coming to, but it had entirely disappeared; so the King repeated angrily, \'or I\'ll have you executed, whether you\'re nervous or not.\' \'I\'m a poor man, your Majesty,\' said Two, in a Little Bill It was the Cat said, waving its tail about in the middle of her head made her so savage when they passed too close, and waving their forepaws to mark the time, while the Dodo managed it.) First it marked out a box of comfits, (luckily the salt water had not got into the book her sister kissed her, and said, very gravely, \'I think, you ought to be almost out of that.', '', 1, '1975-07-02 19:05:12'),
(51, '2018-05-13 10:42:34', 5, 'ALOLO', 'alolo', 'HAHA INI ADALAH KONTEN HAHA HAHA', '1.jpg', 1, '2018-05-13 10:42:34'),
(52, '2018-05-14 15:36:50', 5, 'Halo', 'halo', 'HHHHHHHHHHHHHHHHH', 'gangnam.jpg', 1, '2018-05-14 15:36:50');

-- --------------------------------------------------------

--
-- Struktur dari tabel `categories`
--

CREATE TABLE `categories` (
  `cat_id` int(11) NOT NULL,
  `cat_name` varchar(50) NOT NULL DEFAULT '',
  `cat_description` varchar(255) NOT NULL DEFAULT '',
  `date_created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data untuk tabel `categories`
--

INSERT INTO `categories` (`cat_id`, `cat_name`, `cat_description`, `date_created`) VALUES
(1, 'Music', 'Ini kategori Musik.', '2007-08-16 06:20:42'),
(2, 'Fashion ', 'Ini kategori Fashion.', '1997-07-07 14:13:41'),
(3, 'Game', 'Ini kategori Game.', '2018-01-12 00:48:35'),
(4, 'Art', 'Ini kategori Kesenian.', '2010-08-25 22:03:56'),
(5, 'Artist', 'Ini kategori Artis', '2007-11-16 07:22:00'),
(6, 'Food', 'Ini kategori Makanan.', '1997-08-19 09:14:34'),
(7, 'Drink', 'Ini kategori Minuman.', '2017-07-07 00:07:07'),
(8, 'Webtoon', 'Ini kategori Webtoon Cartoon.', '1986-02-04 13:01:26'),
(9, 'Social Media', 'Ini kategori Sosial Media.', '2003-06-18 11:58:13'),
(10, 'Colour', 'Ini kategori Warna.', '2001-12-04 17:14:20');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blogs`
--
ALTER TABLE `blogs`
  ADD PRIMARY KEY (`post_id`),
  ADD UNIQUE KEY `post_slug` (`post_slug`),
  ADD KEY `cat_id` (`fk_cat_id`);

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`cat_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blogs`
--
ALTER TABLE `blogs`
  MODIFY `post_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;
--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `cat_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
--
-- Ketidakleluasaan untuk tabel pelimpahan (Dumped Tables)
--

--
-- Ketidakleluasaan untuk tabel `blogs`
--
ALTER TABLE `blogs`
  ADD CONSTRAINT `blogs_ibfk_1` FOREIGN KEY (`fk_cat_id`) REFERENCES `categories` (`cat_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
